apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: two-tier-app
data:
  init.sql: |
    -- Your SQL initialization script content goes here
    CREATE DATABASE IF NOT EXISTS mydb;
    USE mydb;
    CREATE TABLE IF NOT EXISTS messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    message TEXT
    );
    -- Add more initialization statements if needed
